"""empty message

Revision ID: 87cd8d16a307
Revises: c841786cd3f8
Create Date: 2019-05-11 15:58:30.695936

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '87cd8d16a307'
down_revision = 'c841786cd3f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'file_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('file_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), nullable=False))
    # ### end Alembic commands ###
