"""empty message

Revision ID: 97ac4a4cc865
Revises: 
Create Date: 2019-05-08 01:37:38.458631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97ac4a4cc865'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(length=64), nullable=True),
    sa.Column('file_loc', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('file_id'),
    sa.UniqueConstraint('file_url')
    )
    op.create_table('menu_item',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=32), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['menu_item.item_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index(op.f('ix_menu_item_item_name'), 'menu_item', ['item_name'], unique=True)
    op.create_table('perm',
    sa.Column('perm_id', sa.Integer(), nullable=False),
    sa.Column('perm_name', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('perm_id')
    )
    op.create_index(op.f('ix_perm_perm_name'), 'perm', ['perm_name'], unique=True)
    op.create_table('role',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_index(op.f('ix_role_role_name'), 'role', ['role_name'], unique=True)
    op.create_table('tag',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('tag_name', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('tag_id')
    )
    op.create_index(op.f('ix_tag_tag_name'), 'tag', ['tag_name'], unique=True)
    op.create_table('menu_link',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_link', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['menu_item.item_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('role_perm',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('perm_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['perm_id'], ['perm.perm_id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.role_id'], ),
    sa.PrimaryKeyConstraint('role_id', 'perm_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_login', sa.String(length=32), nullable=True),
    sa.Column('user_password_hash', sa.String(length=128), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.role_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_user_login'), 'user', ['user_login'], unique=True)
    op.create_table('page',
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('page_title', sa.String(length=64), nullable=True),
    sa.Column('page_url', sa.String(length=64), nullable=True),
    sa.Column('page_timestamp', sa.DateTime(), nullable=True),
    sa.Column('page_visible', sa.Boolean(), nullable=True),
    sa.Column('page_preview', sa.Text(), nullable=True),
    sa.Column('page_content', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('page_id'),
    sa.UniqueConstraint('page_url')
    )
    op.create_index(op.f('ix_page_page_timestamp'), 'page', ['page_timestamp'], unique=False)
    op.create_index(op.f('ix_page_page_title'), 'page', ['page_title'], unique=True)
    op.create_index(op.f('ix_page_page_visible'), 'page', ['page_visible'], unique=False)
    op.create_table('menu_page',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['menu_item.item_id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['page.page_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('page_file',
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file.file_id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['page.page_id'], ),
    sa.PrimaryKeyConstraint('page_id', 'file_id')
    )
    op.create_table('page_tag',
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['page.page_id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.tag_id'], ),
    sa.PrimaryKeyConstraint('page_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('page_tag')
    op.drop_table('page_file')
    op.drop_table('menu_page')
    op.drop_index(op.f('ix_page_page_visible'), table_name='page')
    op.drop_index(op.f('ix_page_page_title'), table_name='page')
    op.drop_index(op.f('ix_page_page_timestamp'), table_name='page')
    op.drop_table('page')
    op.drop_index(op.f('ix_user_user_login'), table_name='user')
    op.drop_table('user')
    op.drop_table('role_perm')
    op.drop_table('menu_link')
    op.drop_index(op.f('ix_tag_tag_name'), table_name='tag')
    op.drop_table('tag')
    op.drop_index(op.f('ix_role_role_name'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_perm_perm_name'), table_name='perm')
    op.drop_table('perm')
    op.drop_index(op.f('ix_menu_item_item_name'), table_name='menu_item')
    op.drop_table('menu_item')
    op.drop_table('file')
    # ### end Alembic commands ###
