"""empty message

Revision ID: 983080ceaaae
Revises: 87cd8d16a307
Create Date: 2019-05-11 19:38:15.018220

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '983080ceaaae'
down_revision = '87cd8d16a307'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link',
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('link_url', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('link_id')
    )
    op.add_column('menu_link', sa.Column('link_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'menu_link', 'link', ['link_id'], ['link_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('menu_link', 'item_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_link', sa.Column('item_link', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), nullable=False))
    op.drop_constraint(None, 'menu_link', type_='foreignkey')
    op.drop_column('menu_link', 'link_id')
    op.drop_table('link')
    # ### end Alembic commands ###
