"""empty message

Revision ID: c841786cd3f8
Revises: 9c0ca79dca49
Create Date: 2019-05-11 15:18:21.350428

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c841786cd3f8'
down_revision = '9c0ca79dca49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('file_name', sa.String(length=128), nullable=False))
    op.add_column('file', sa.Column('file_path', sa.String(length=128), nullable=False))
    op.drop_column('file', 'file_loc')
    op.drop_constraint('menu_item_ibfk_1', 'menu_item', type_='foreignkey')
    op.create_foreign_key(None, 'menu_item', 'menu_item', ['parent_id'], ['item_id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_constraint('menu_link_ibfk_1', 'menu_link', type_='foreignkey')
    op.create_foreign_key(None, 'menu_link', 'menu_item', ['item_id'], ['item_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('menu_page_ibfk_2', 'menu_page', type_='foreignkey')
    op.drop_constraint('menu_page_ibfk_1', 'menu_page', type_='foreignkey')
    op.create_foreign_key(None, 'menu_page', 'menu_item', ['item_id'], ['item_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'menu_page', 'page', ['page_id'], ['page_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('page_ibfk_1', 'page', type_='foreignkey')
    op.create_foreign_key(None, 'page', 'user', ['user_id'], ['user_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('page_file_ibfk_2', 'page_file', type_='foreignkey')
    op.drop_constraint('page_file_ibfk_1', 'page_file', type_='foreignkey')
    op.create_foreign_key(None, 'page_file', 'file', ['file_id'], ['file_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'page_file', 'page', ['page_id'], ['page_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('page_tag_ibfk_1', 'page_tag', type_='foreignkey')
    op.drop_constraint('page_tag_ibfk_2', 'page_tag', type_='foreignkey')
    op.create_foreign_key(None, 'page_tag', 'page', ['page_id'], ['page_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'page_tag', 'tag', ['tag_id'], ['tag_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('role_perm_ibfk_1', 'role_perm', type_='foreignkey')
    op.drop_constraint('role_perm_ibfk_2', 'role_perm', type_='foreignkey')
    op.create_foreign_key(None, 'role_perm', 'role', ['role_id'], ['role_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'role_perm', 'perm', ['perm_id'], ['perm_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('user', 'role_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('user', 'user_password_hash',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128),
               nullable=False)
    op.drop_constraint('user_ibfk_1', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'role', ['role_id'], ['role_id'], onupdate='CASCADE', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('user_ibfk_1', 'user', 'role', ['role_id'], ['role_id'])
    op.alter_column('user', 'user_password_hash',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128),
               nullable=True)
    op.alter_column('user', 'role_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_constraint(None, 'role_perm', type_='foreignkey')
    op.drop_constraint(None, 'role_perm', type_='foreignkey')
    op.create_foreign_key('role_perm_ibfk_2', 'role_perm', 'role', ['role_id'], ['role_id'])
    op.create_foreign_key('role_perm_ibfk_1', 'role_perm', 'perm', ['perm_id'], ['perm_id'])
    op.drop_constraint(None, 'page_tag', type_='foreignkey')
    op.drop_constraint(None, 'page_tag', type_='foreignkey')
    op.create_foreign_key('page_tag_ibfk_2', 'page_tag', 'tag', ['tag_id'], ['tag_id'])
    op.create_foreign_key('page_tag_ibfk_1', 'page_tag', 'page', ['page_id'], ['page_id'])
    op.drop_constraint(None, 'page_file', type_='foreignkey')
    op.drop_constraint(None, 'page_file', type_='foreignkey')
    op.create_foreign_key('page_file_ibfk_1', 'page_file', 'file', ['file_id'], ['file_id'])
    op.create_foreign_key('page_file_ibfk_2', 'page_file', 'page', ['page_id'], ['page_id'])
    op.drop_constraint(None, 'page', type_='foreignkey')
    op.create_foreign_key('page_ibfk_1', 'page', 'user', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'menu_page', type_='foreignkey')
    op.drop_constraint(None, 'menu_page', type_='foreignkey')
    op.create_foreign_key('menu_page_ibfk_1', 'menu_page', 'menu_item', ['item_id'], ['item_id'])
    op.create_foreign_key('menu_page_ibfk_2', 'menu_page', 'page', ['page_id'], ['page_id'])
    op.drop_constraint(None, 'menu_link', type_='foreignkey')
    op.create_foreign_key('menu_link_ibfk_1', 'menu_link', 'menu_item', ['item_id'], ['item_id'])
    op.drop_constraint(None, 'menu_item', type_='foreignkey')
    op.create_foreign_key('menu_item_ibfk_1', 'menu_item', 'menu_item', ['parent_id'], ['item_id'])
    op.add_column('file', sa.Column('file_loc', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), nullable=False))
    op.drop_column('file', 'file_path')
    op.drop_column('file', 'file_name')
    # ### end Alembic commands ###
